### ISSUE TITLE
value as a textarea

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-key-value-editor#14]
Some values may be quite a bit larger and require a textbox instead of an input.

@rhamilto im adding as issues so we can work on them if we divvy out anything

**Comment by rhamilto** [comment]
Questions:

* do only values get the textarea?  or both the key and the value?
* configurable on a per editor instance?
* configurable on a per key/value pair instance?

**Comment by rhamilto** [comment]
Need to identify the use cases for a textarea in origin-web-console.

**Comment by rhamilto** [comment]
Per @jwforres, we don't have known need for this yet, so we can make this the lowest priority.

**Comment by benjaminapetersen** [comment]
agree
