### ISSUE TITLE
ng-messages for form validation messages

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-key-value-editor#15]
It may be helpful to add text messages to the validation, rather than just a red border on the input.  The `ng-messages` directive is useful for this.

**Comment by rhamilto** [comment]
You already added text messages, no?
![screen shot 2016-06-15 at 9 37 11 am](https://cloud.githubusercontent.com/assets/895728/16081735/bef4c634-32dc-11e6-9bf0-34029eac48a5.PNG)

**Comment by benjaminapetersen** [comment]
yup. didn't use ng-messages, i think thats supposed to help if we have multiple different validation types... possibly more relevant now that we have custom validation + min-lenght + max-length support... but will need to look again.  Maybe this isn't relevant anymore.
