### ISSUE TITLE
Create a picker directive for complex key value pairs

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-key-value-editor#31]
In the web console of openshift we will have key value pars where the value is a complex object (something like choosing a value from a secret, or from a config map).  This directive needs to be able to take an array of data to "choose" from, or _perhaps_ take a url that would allow it to fetch data to then present as a picker.

I'm leaning towards no HTTP calls, that should be provided by calling code (controller).

**Comment by benjaminapetersen** [comment]
One current impl is this:
https://github.com/openshift/origin-web-console/blob/master/app/views/directives/environment.html
https://github.com/openshift/origin-web-console/blob/master/app/scripts/directives/resources.js#L141

**Comment by benjaminapetersen** [comment]
@jhadvig @rhamilto and I got a Q for you.  We are building a small set of directives out to improve key-value editing in the web console.  One thing we need to do is to be able to pick a value from a config map or secret.  I pasted a couple links above for the current environments template that shows them.

Can you point us in a good direction to reproduce a situation where we would see some of this in the UI?
Thx!

**Comment by jhadvig** [comment]
@benjaminapetersen @rhamilto here are the `configMapKeyRef` scenario:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/docs/user-guide/configmap/command-pod.yaml
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/docs/user-guide/configmap/env-pod.yaml

Here is the `secretRef` scenario:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/docs/user-guide/secrets/secret-env-pod.yaml

Here is the `fieldRef`:
https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/docs/user-guide/downward-api/dapi-pod.yaml

For all of them you just need to paste the yaml file to the ace editor in the `From File` tab, on the 'Add to project' page. Then just go to the Browse -> Pods and 'Environement' should display those values :)

Hopefully that helps :smile:  ... can't wait what you guys come up with, so far the editor look awesome :heart:

**Comment by benjaminapetersen** [comment]
Perfect, thx @jhadvig !

**Comment by benjaminapetersen** [comment]
Adding a screenshot of the env table here for reference:

![screen shot 2016-06-15 at 10 30 07 am](https://cloud.githubusercontent.com/assets/280512/16083766/35c0b26c-32e4-11e6-8b20-179747d0c86c.png)

**Comment by rhamilto** [comment]
Additional screenshots so all the aforementioned cases are included.

![screen shot 2016-06-15 at 11 41 52 am](https://cloud.githubusercontent.com/assets/895728/16086704/796f313c-32ee-11e6-9a85-04fcb70c8153.PNG)
![screen shot 2016-06-15 at 11 41 37 am](https://cloud.githubusercontent.com/assets/895728/16086703/796d8d8c-32ee-11e6-9455-232e9cfa49f9.PNG)
![screen shot 2016-06-15 at 11 41 28 am](https://cloud.githubusercontent.com/assets/895728/16086705/79758064-32ee-11e6-8165-0a848cfc58dd.PNG)

**Comment by rhamilto** [comment]
@jwforres, in looking to implement this new editor in the console, I discovered that env vars are not currently editable for pods (when trying to edit them via "Edit YAML", I get an error stating "Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`").  Does that mean we don't need to do this or that env vars for pods will be editable in the future?

**Comment by jwforres** [comment]
env vars for pods will never be editable, only DCs, RCs, and BCs

**Comment by jwforres** [comment]
It's debatable whether we should let you edit env on an RC that came from a
deployment config, we generally try to push you into editing the DC and
creating a new deployment instead, that way you get the benefit of rolling
out the change to a new set of pods.  Otherwise you have to manually delete
pods or scale down to zero and scale back up in order for the new Env to be
applied.  Probably need a warning when editing Env on RC's that didnt come
from a DC (we shouldn't prevent you from doing it in this case)  that
explains that they will need to either delete their current pods or scale
up / scale down to get the Env change applied.

**Comment by benjaminapetersen** [comment]
[Relevant web console issue](https://github.com/openshift/origin-web-console/issues/277)
