### ISSUE TITLE
'is-readonly' attribute should take boolean

### ISSUE THREAD

**Issue by jhadvig** [openshift/angular-key-value-editor#78]
'is-readonly' attribute should take boolean, since the there are cases we want to have the envVar editor readlony and cases we don't.
Eg: different users have different actions allowed, so when checking user's permissions we would pass the result into the attribute

**Comment by benjaminapetersen** [comment]
Looking @ this.  If you need a quick and dirty workaround, could do something like this:
```html
<key-value-editor
  ng-if="canEditStuff"></key-value-editor>
<key-value-editor
  ng-if="(!canEditStuff)"
  is-readonly></key-value-editor>
```
so long as `canEditStuff` is `true||false` it should swap render between the two instances.

**Comment by benjaminapetersen** [comment]
The real fix is probably for me to update the `$watch` on `is-readonly`.  Currently it supports either `is-readonly` (exists is truthy) or `is-readonly="['foo', 'bar']"`, which would make individual entries readonly.

**Comment by jhadvig** [comment]
@benjaminapetersen yeah I wanted to avoid the dup that the first workaround introduces since you will have basically this https://github.com/openshift/origin-web-console/blob/master/app/views/browse/build-config.html#L400-L406 two times :flushed:
But will probably have to do it with some TODO comment and when you have fix will remove and add the check.
Thoughts ?

**Comment by jhadvig** [comment]
Ohh sorry just read your mail. Will wait and fix afterwards !!! Thanks Ben !!!! :)

**Comment by benjaminapetersen** [comment]
@jhadvig sorry haven't got this one yet!  been on a couple high priority bugs.  Hope having to deal with that workaround for this little bit hasn't been awful.  Def still on the radar!

**Comment by benjaminapetersen** [comment]
Adding to the case in favor of the boolean, while html readonly is: 
```html
<input value="foo" READONLY>
``` 
Angular has a ton of directives like it that take booleans:
```html
<div ng-if="bool"></div>
<div ng-show="bool"></div>
<div ng-hide="bool"></div>
```
as well as `ng-checked`, `ng-cloak`,`ng-disabled`, `ng-readonly`, etc. 

Def seems the right direction to make this change.
